swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths 
basePath: /apis/v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /login:
    x-swagger-router-controller: authentication_controller
    post:
      description: If the given credentials is valid, returns a session string
      operationId: login
      parameters:
        - name: username
          in: query
          description: The username of the account
          required: true
          type: string
        - name: password
          in: query
          description: The password of the account
          required: true
          type: string
      responses:
        "200": 
          description: Success
          schema:
            # TODO: Create a schema for all responses
        "422":
          description: Failed due to incorrect username or password
          schema: 
            # TODO: Create a schema for all responses
        "500":
          description: Internal Error
          schema: 
            # TODO: Create a schema for all responses
  /register:
    x-swagger-router-controller: user_controller
    post:
      description: Creates a new User object based on the details given
      operationId: create_user
      parameters:
        # Account Credentials
        - name: username
          in: query
          description: The username the user wants to access the web account
          type: string
          required: true
        - name: password
          in: query
          description: The password the user wants to access the web account
          type: string
          required: true
        
        # Personal Details
        - name: firstName
          in: query
          description: The firstname of the user
          type: string
          required: true
        - name: lastName
          in: query
          description: The lastname of the user
          type: string
          required: true
        - name: middleName
          in: query
          description: The middle of the user
          type: string
          required: true
        - name: suffix
          in: query
          description: The suffix of the user, if any
          type: string
          required: false
        - name: religion
          in: query
          description: The religion of the user
          type: string
          required: true
        - name: citizenship
          in: query
          description: The citizenship of the user
          type: string
          required: true
        - name: dateOfBirth
          in: query
          description: The Date of Birth of the user
          type: string
          required: true
        - name: birthPlace
          in: query
          description: The Birth Place of the user
          type: string
          required: true

        # Address
      responses:
        "200": 
          description: Success
          schema:
            $ref: "#/definitions/Response"
        "422":
          description: Failed due to incorrect username or password
          schema: 
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Internal Error
          schema: 
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Response:
    properties:
      iat:
        type: number
      payload:
        type: Object
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - errors
    properties:
      iat: 
        type: number
      errors:
        type: array
